export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"



export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST"
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS"
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL"


export const ORDER_DEATILS_REQUEST = "ORDER_DEATILS_REQUEST"
export const ORDER_DEATILS_SUCCESS = "ORDER_DEATILS_SUCCESS"
export const ORDER_DEATILS_FAIL = "ORDER_DEATILS_FAIL"



export const ALL_ORDER_DEATILS_REQUEST = "ALL_ORDER_DEATILS_REQUEST"
export const ALL_ORDER_DEATILS_SUCCESS = "ALL_ORDER_DEATILS_SUCCESS"
export const ALL_ORDER_DEATILS_FAIL = "ALL_ORDER_DEATILS_FAIL"








export const CLEAR_ERRORS = "CLEAR_ERRORS"


